spring.application.name=SB Auth System

# ================= DATABASE =================
spring.datasource.url=jdbc:postgresql://localhost:5432/your_db_name
spring.datasource.username=your_username
spring.datasource.password=your_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ================= JWT =================
app.jwt.secret=your_jwt_secret_key
app.jwt.expiration-ms=86400000

# ================= REDIS =================
# redis-server
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ================= OAUTH2 GOOGLE =================
# http://localhost:8080/oauth2/authorization/google
spring.security.oauth2.client.registration.google.client-id=your_google_client_id
spring.security.oauth2.client.registration.google.client-secret=your_google_client_secret
spring.security.oauth2.client.registration.google.scope=email,profile

# ================= SWAGGER =================
# http://localhost:8080/swagger-ui/index.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ================= RabbitMQ =================
# http://localhost:15672
# rabbitmq-service start
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ================= Email Sender =================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
# USE THE 16-CHARACTER APP PASSWORD HERE, NOT YOUR REAL PASSWORD
spring.mail.password=xxxx xxxx xxxx xxxx 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

