spring.application.name=SB Auth System

spring.datasource.url=jdbc:postgresql://localhost:5432/SBAuthSys
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
